### ISSUE TITLE
how to run

### ISSUE THREAD

**Issue by lizheng-1** [mattochal/imbalanced_fsl_public#1]
I want to know how to train my own data set, for example Omniglot

**Comment by mattochal** [comment]
Hi there! Thank you for your interest! 

The easiest way to train on a custom dataset is as follows.

## Place your images in a directory substructure

For instance place your images in the `data/custom` folder, as described [here](https://github.com/mattochal/imbalanced_fsl_public/blob/master/data/README.md#create-from-a-class-subdirectory-structure). 

## Cache or load from disk
Then, you may want to do one of two things depending on your RAM allowance and dataset sizes.

### Option 1. Recommended if your dataset fits in RAM. 

Create cache files using `python create_cache_from_folders.py custom` 

### Option 2. Slower training time but less RAM used

Load the dataset directly from the disk during training. For instance, you can enable this by adding `"dataset_args.use_cache":[False]` in the `generator.py` file around lines [here](https://github.com/mattochal/imbalanced_fsl_public/blob/cbe8de1423df9654c922078e7180195c5637383d/generator.py#L262)

## Finally
Then, regenerate the configuration files, e.g. using `python generator.py --imbalanced_supports --dataset custom`
